###

GET http://localhost:3001/api/session HTTP/1.1

###

POST http://localhost:3001/api/signup HTTP/1.1
Content-Type: application/json

{
    "name":         "Ciclarimpo",
    "email":        "ciclarimpo@gymapp.dev",
    "username":     "ciclarimpo",
    "password":     "password",
    "birthdate":    "01-01-0001"
}

###

GET http://localhost:3001/api/logout HTTP/1.1

###


GET http://localhost:3001/api/bia/ HTTP/1.1

###

POST http://localhost:3001/api/bia/ HTTP/1.1
Content-Type: application/json

{
    "bmi": 28.9,
    "na_k": 0.9,
    "weight": 84.2,
    "height": 178,
    "fat_mass": 13.2,
    "phase_angle": 7.6,
    "muscle_mass": 60.4,
    "date": "08-31-2024",
    "fat_free_mass": 75.0,
    "total_body_water": 55.1,
    "extra_cellular_water": 21.7,
    "intra_cellular_water": 33.4,
    "skeletal_muscle_mass": 40.3,
    "basal_metabolic_rate": 2072.4,
    "body_composition_measurement": 45.6,
    "total_daily_energy_expenditure": 3523.1,
    "appendicular_skeletal_muscle_mass": 31.0
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "bankich",
    "password": "password"
}

###

GET http://localhost:3001/api/meals?weekday=2&meal=3 HTTP/1.1

###